# Generated by Django 5.2.5 on 2025-11-15 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_variations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variations",
            old_name="variation_value",
            new_name="color",
        ),
        migrations.RenameField(
            model_name="variations",
            old_name="variation_category",
            new_name="size",
        ),
    ]
