# Generated by Django 5.2.5 on 2025-11-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_rename_variation_value_variations_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variations",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("extra_large", "Extra Large"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variations",
            unique_together={("product", "color", "size")},
        ),
    ]
