# Generated by Django 5.2.5 on 2025-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0005_alter_variations_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variations"),
        ),
    ]
